version: '3.8'

services:
  bot:
    container_name: bot-trading-crypto
    build: .
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TOKEN=${TOKEN}
      - CHANNEL=${CHANNEL}
      - AMOUNT_TO_SPEND=${AMOUNT_TO_SPEND}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:6.2
    container_name: redis-trading-crypto
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
